post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1Y2ZkNjE4NDRlOGI2MjFmZTVjMzZmYzYiLCJpYXQiOjE1NjAxNDA4NjN9.B6XSx4XGNEmASsBvz4W3jZ-DM5Bm2hTKBxz3gs2l7OQ

{
  "content": "Single Page Apps use token authentication",
  "important": true
}